// Step 1 Workbook Questions
export const WORKBOOK_STEP1_QUESTIONS = [
    { title: "Part 1: Powerlessness", isSection: true },
    "In your own words, what does powerless mean to you regarding cocaine and all other mind-altering substances?",
    "Describe your attempts to control your use. Did you ever set rules like only using on weekends, never using alone, or only buying a certain amount? What was the result?",
    "Once you start using, can you reliably control the amount you'll take or how long the run will last? Share examples of times you used much more than you planned.",
    "Have you ever made sincere promises to yourself or others that you would stop, only to use again? How did breaking those promises make you feel?",
    "How much of your daily thinking was obsessed with cocaine? (e.g., planning how to get it, finding the money, hiding your use, and recovering from the crash).",
    "Did you ever continue to use even when you knew it would lead to negative consequences with your job, family, or health?",
    "Have you done things while high or seeking drugs that went against your core values and filled you with shame or regret afterward?",
    "Describe the physical craving you've experienced for cocaine. What did it feel like when the obsession to use hit you?",
    "How did your personality change when you were using? Did you become paranoid, irritable, arrogant, or withdrawn?",
    "Why haven't willpower and self-knowledge been enough to keep you from using?",
    { title: "Part 2: Unmanageability", isSection: true },
    "What does unmanageable mean in the context of your life? List five specific examples of how your life became unmanageable.",
    "How has your drug use damaged your relationships with the people who care about you? Have dishonesty and unreliability become normal?",
    "In what ways did your use affect your job or school performance? Have you lost a job, been disciplined, or dropped out because of it?",
    "Be brutally honest about the financial cost of your addiction. How much money has it consumed? Have you gone into debt, sold possessions, or stolen to support your habit?",
    "How has your use impacted your physical health? (Consider the crash, nosebleeds, weight loss, heart palpitations, lack of sleep, or other serious health issues).",
    "What has been the effect of your use on your mental and emotional health? (Describe feelings of paranoia, anxiety, severe depression, hopelessness, or fear).",
    "Have you neglected important responsibilities? (e.g., personal hygiene, paying bills, caring for your home or children).",
    "Has your addiction ever put you or others in dangerous situations? (e.g., driving high, associating with dangerous people, unsafe sex).",
    "Did you start isolating yourself or avoiding people and situations where you couldn't be high?",
    "How has your addiction impacted your spiritual life? Do you feel a sense of emptiness or disconnection from your own moral compass?",
    { title: "Part 3: Acceptance and Surrender", isSection: true },
    "What doubts or reservations do you still have about admitting you are an addict? What are you afraid of losing?",
    "What have been the consequences of denying the severity of your problem?",
    "Looking back, can you identify when your use crossed the line from a \"party\" to a destructive obsession?",
    "If nothing changes, what will your life look like in one year? In five years?",
    "Do you truly believe, deep down, that you are powerless over cocaine and that your life has become unmanageable? Why is this total surrender the essential first step toward freedom?"
];

// Step 2 Workbook Questions
export const WORKBOOK_STEP2_QUESTIONS = [
    { title: "Part 1: Understanding Insanity", isSection: true },
    "In your own words, what does “insanity” mean when it comes to addiction? (Think of the cycle of repeating the same destructive behavior while expecting different results.)",
    "What specific behaviors or thought patterns in your addiction could be considered “insane”? (Examples: lying to yourself, believing you could control it next time, thinking one hit wouldn’t hurt.)",
    "How did your thinking become distorted while using? (Did you justify, minimize, or deny consequences?)",
    "Can you describe times when you made irrational or risky decisions because of your addiction?",
    "How did you try to manage or control your use after things clearly became unmanageable? What were the results?",
    "In what ways did your addiction separate you from reality, your loved ones, or your true self?",
    "When you think about your life during active addiction, what evidence shows that your best thinking wasn’t enough to keep you safe or sober?",
    { title: "Part 2: Coming to Believe", isSection: true },
    "What does the phrase “came to believe” mean to you personally? Does it suggest a process or a sudden realization?",
    "What are your current beliefs about a Power greater than yourself? (This can be God, nature, the universe, the fellowship, or even the collective strength of others in recovery.)",
    "Have you ever experienced something greater than yourself helping you through a difficult time — even before recovery?",
    "What are some moments in early recovery where you’ve seen evidence of something working in your life that isn’t just your own willpower?",
    "How does the idea of surrendering control make you feel — fearful, hopeful, relieved, or resistant?",
    "What people, places, or experiences have helped you begin to trust that change is possible?",
    "How does seeing others in recovery influence your belief that you can also recover?",
    { title: "Part 3: Restoration to Sanity", isSection: true },
    "What does “sanity” look like to you? How would a sane and balanced life differ from your old patterns?",
    "In what areas of your life do you feel restoration is already beginning?",
    "How do you imagine a Power greater than yourself could help you heal your thinking and behavior?",
    "What does spiritual growth or awakening mean to you at this stage of recovery?",
    "What signs of hope have you experienced since beginning this journey?",
    "What would it mean to truly trust the recovery process instead of trying to control it?",
    "How would your life look if you allowed yourself to fully believe that recovery — and peace of mind — are possible for you?",
    { title: "Part 4: Acceptance and Openness", isSection: true },
    "What fears or doubts do you still have about turning your life over to a Power greater than yourself?",
    "What is holding you back from fully believing that you can be restored to sanity?",
    "What would you need to let go of to move forward in faith?",
    "How can you stay open-minded as you continue to explore your own understanding of a Higher Power?",
    "How do you plan to strengthen your spiritual connection moving into Step Three?",
];

// Step 3 Workbook Questions
export const WORKBOOK_STEP3_QUESTIONS = [
    { title: "Part 1: Understanding the Decision", isSection: true },
    "In your own words, what does “making a decision” mean in the context of recovery? (Is it a feeling, an action, a surrender, or all three?)",
    "How do you understand the difference between believing in a Higher Power (Step Two) and deciding to turn your will and life over (Step Three)?",
    "What fears or reservations do you have about giving up control of your will and life?",
    "What does “your will” mean to you? How have self-will, pride, or ego influenced your past decisions?",
    "What has been the result when you tried to control everything yourself?",
    "In what areas of your life do you still struggle to let go and trust a Power greater than yourself?",
    "What might your life look like if you truly surrendered those areas to spiritual care and guidance?",
    { title: "Part 2: Turning It Over", isSection: true },
    "What does “turning your will and your life over” look like in practical terms for you?",
    "How can you begin to rely on a Higher Power instead of your own impulses and fears?",
    "Have you experienced moments when you felt genuine guidance, peace, or strength beyond yourself? Describe them.",
    "What actions or daily practices can help you maintain this connection (e.g., prayer, meditation, service, honesty)?",
    "What would it take for you to fully trust that this Power wants what’s best for you?",
    "How does humility play a role in Step Three?",
    "What does it mean to you to live “in God’s care” rather than under your own direction?",
    { title: "Part 3: Willingness and Action", isSection: true },
    "How do you know when you are being guided by self-will instead of spiritual will?",
    "What are some signs that you are resisting guidance or trying to take back control?",
    "How do you feel when you finally let go of something you’ve been clinging to?",
    "What actions can you take today to show your willingness to live according to spiritual principles rather than your old habits?",
    "How do prayer and meditation (or quiet reflection) help you align your will with your Higher Power’s will?",
    "How can you remind yourself each day that surrender is not weakness, but strength?",
    "How might turning your will and life over improve your relationships with others?",
    { title: "Part 4: Faith and Trust", isSection: true },
    "What does faith mean to you — and how has it changed since entering recovery?",
    "What does “trusting the process” look like in your daily life?",
    "How can you show gratitude for the guidance and care you’re beginning to experience?",
    "What would it feel like to live with complete trust in your Higher Power?",
    "How do you handle doubt or fear when you feel disconnected from that Power?",
    "Who or what helps you stay accountable to your decision to live spiritually?",
    "What is one situation right now that you can practice turning over — fully — to your Higher Power?",
    { title: "Part 5: Commitment and Renewal", isSection: true },
    "Have you said or written your own version of the Step Three prayer? What does it mean to you personally?",
    "How can you demonstrate your decision to turn your will and life over in your everyday choices?",
    "What kind of person do you believe your Higher Power is helping you become?",
    "How do you want your recovery to reflect your growing faith and surrender?",
    "How will you keep renewing this decision — one day at a time?",
];

// Step 4 Workbook Questions
export const WORKBOOK_STEP4_QUESTIONS = [
    { title: "Part 1: Understanding Moral Inventory", isSection: true },
    "What does the phrase 'searching and fearless moral inventory' mean to you?",
    "Why do you think it’s important to examine your resentments, fears, and harms to others?",
    "What do you hope to gain from doing this inventory honestly?",
    "What fears or hesitations do you have about doing Step Four?",
    "How does honesty with yourself play a role in your recovery process?",
    { title: "Part 2: Resentments", isSection: true },
    "List the people, institutions, or principles you resent. What did they do to cause the resentment?",
    "How did each resentment affect your pride, self-esteem, security, ambitions, relationships, or sex life?",
    "What part did you play in each situation? Were you selfish, dishonest, fearful, or inconsiderate?",
    "Have you been holding onto any old grudges that continue to poison your peace of mind?",
    "What patterns can you identify in your resentments? What do they reveal about you?",
    { title: "Part 3: Fears", isSection: true },
    "What are your greatest fears—past, present, and future?",
    "How have your fears influenced your decisions and behavior?",
    "Have you ever allowed fear to control your actions or relationships? Give examples.",
    "What do your fears reveal about your lack of faith or trust in a Higher Power?",
    "How might facing your fears honestly bring you closer to spiritual freedom?",
    { title: "Part 4: Harms to Others", isSection: true },
    "List people you have harmed through your addiction or behavior.",
    "What specific actions did you take that hurt them (lying, manipulation, neglect, theft, etc.)?",
    "How did these actions affect those people emotionally, financially, or spiritually?",
    "What part of your character was at play in each harm (selfishness, pride, fear, anger)?",
    "How does recognizing these harms help prepare you for making amends later in Step Eight?",
    { title: "Part 5: Character Defects", isSection: true },
    "What recurring traits or attitudes keep causing problems in your life (dishonesty, jealousy, self-pity, etc.)?",
    "How have these defects shown up in your relationships and decisions?",
    "In what ways have these traits protected you or helped you survive in the past?",
    "Are you willing to let go of these defects, even the ones you think you 'need'? Why or why not?",
    "What would your life look like without these destructive patterns dominating your thoughts and actions?",
];

// Step 5 Workbook Questions
export const WORKBOOK_STEP5_QUESTIONS = [
    { title: "Part 1: Understanding Step Five", isSection: true },
    "What does Step Five mean to you personally?",
    "Why do you think it’s necessary to share your moral inventory with another person?",
    "How does admitting your wrongs to God, yourself, and another human being help you heal?",
    "What fears or doubts do you have about being completely honest in this step?",
    "What do you hope to gain from completing Step Five?",
    { title: "Part 2: Preparation for Step Five", isSection: true },
    "Who have you chosen to share your Step Four inventory with, and why did you choose them?",
    "What qualities make this person trustworthy and supportive of your recovery?",
    "What steps can you take to prepare emotionally and spiritually for this conversation?",
    "Are there any parts of your inventory you still feel hesitant or ashamed to share?",
    "What might happen if you hold back certain truths during your Step Five?",
    { title: "Part 3: The Experience of Sharing", isSection: true },
    "Describe what it felt like to share your inventory openly with another person.",
    "Were there any surprises or realizations during the conversation?",
    "Did the person you shared with offer insights or perspectives you hadn’t considered before?",
    "How did it feel to be truly honest about things you’ve hidden or denied for years?",
    "What emotions surfaced during or after your Step Five discussion (e.g., relief, guilt, peace, freedom)?",
    { title: "Part 4: Insights and Lessons Learned", isSection: true },
    "What did you learn about yourself through this process?",
    "How did Step Five change your understanding of humility and accountability?",
    "What patterns of behavior or thinking became clearer after sharing your wrongs out loud?",
    "How has this step affected your sense of connection with your Higher Power?",
    "Do you feel lighter or more at peace now that you’ve shared your secrets? Explain.",
    { title: "Part 5: Moving Forward", isSection: true },
    "What areas of your life feel ready for healing now that you’ve completed Step Five?",
    "Are there amends or changes in behavior you already feel motivated to make?",
    "What practices will help you maintain honesty and humility going forward?",
    "How will you remind yourself to keep an open heart and mind as you continue with the Steps?",
    "In what ways do you feel closer to freedom, forgiveness, and inner peace after completing Step Five?",
];